### ISSUE TITLE
Improve hovercards

### ISSUE THREAD

**Issue by okjuan** [okjuan/vbook#6]
## fix bugs
- [ ] keeping hovercard open by hovering over it is impossible if link is split across a newline (see screenshot 1) below
- [ ] fix perf issues that remain despite my [recent optimization](https://github.com/okjuan/vbook/pull/8)
- [x] addressed by #8 ~~fix issue where local builds take a long time presumably because hovercards are being recursively built~~
- [x] addressed by #8 ~~fix issue where local dev reloads add multiple levels of `div.paragraph` wrappers, which cause newlines to be insert before and after hovercard hyperlinks~~
- [x] addressed by #8 ~~prevent hovercards from appearing within hovercards; right now, whether a hovercard opens within a hovercard depends on which order the hovercards are inserted during the build process~~
- [x] addressed by #8 ~~design for case where user hovers over hoverlink inside an existing hovercard~~
- [x] addressed by #7 ~~prevent hovercards from appearing on mobile~~

## improve hover UX
- [x] addressed by #7 ~~make the hover-link pseudo-element bigger~~
- [x] addressed by #7 ~~don't open hovercard when cursor is not near (or very close to) hyperlink~~
- [x] addressed by #7 ~~position hovercard above link if link is near bottom of viewport~~
- [x] addressed by #7 ~~similar to the above, position hovercard to the left if link is near right of viewport~~
- [x] addressed by #11 ~~make spacing offset (and its implementation) of hovercards consistent: same vertical and horizontal distance from link for all four positions of hovercards~~
- [x] fixed by setting "Show scrollbars" only "When scrolling" on my Mac (see screenshot 2 below) ~~hide ugly white scrollbar UI~~
- [ ] consider changing behavior from on-hover, to on-click like [the OG wiki](https://wiki.c2.com/)
- [ ] prevent flash when hovercard gets moved from default bottom right position to another position
- [ ] use `MutationObserver` instead of `IntersectionObserver` to fix bug where hover-link at very bottom of page does not have hover card in view and thus is not in scope of `IntersectionObserver`
- [ ] improve case where links are very close to each other e.g. bullet list in https://okjuan.me/vbook/now-dec-24-2023

## other
- [ ] implement hovercards for other scenarios e.g. post previews
- [ ] allow hovercard to expand to its max-width when there is space
- [ ] style hyperlinks differently if linking within site
- [ ] add a delay and/or animation to show card when user hovers over link
- [ ] (possibly) tweak hover card design: add a little arrow shape between link and card

## screenshot 1

![image](https://github.com/okjuan/vbook/assets/13096220/65abd358-34c3-4d17-94e7-93e14f107bda)

## screenshot 2

![image](https://github.com/okjuan/vbook/assets/13096220/f33976ca-46ce-48b0-a208-bde77ce1f587)
